name = "staffsway-backend"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "staffsway-db"
database_id = "9335cd14-464c-4585-bdab-ed89d56e539f"
migrations_dir = "migrations"
migrations_table = "d1_migrations"
