name = "staffsway-backend"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

migrations_dir = "migrations"

[[d1_databases]]
binding = "DB"
database_name = "staffsway-demo"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_table = "d1_migrations"
